version: "3"

# 虚拟网络
networks:
  db_network:
    driver: bridge

services:
  # mysql服务
  db:
    image: mysql:8.0.35
    # 文件读取环境变量
    env_file:
      - ./mysql/.env
    # 直接设置环境变量
    environment:
      - TZ=Asia/Shanghai
    # 挂载数据卷
    volumes:
      - ./mysql/data:/var/lib/mysql # 数据
      - ./mysql/my.cnf:/etc/mysql/my.cnf # 配置文件
      - ./mysql/sql:/sql # sql文件目录
    ports:
      - "3306:3306"
    networks:
      - db_network
    restart: unless-stopped # 重启策略，除手动停止外自动重启

  # redis服务
  redis:
    image: redis:7.2.3
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf # 配置文件
    ports:
      - "6379:6379"
    networks:
      - db_network
    restart: unless-stopped # 重启策略，除手动停止外自动重启
